language: python
python:
  - "2.7"
  - "3.4"
install:
  - "pip install coveralls"
  - "pip install codecov"
  - "pip install -e .[test]"
script:
  - py.test
  - coverage run --source=testpy -m py.test
after_success:
  - coveralls
  - codecov
sudo: false
